apiVersion: v1
appVersion: "1.0"
description: Presslabs open source stack for deploying scalable WordPress on kubernetes
name: presslabs-stack
version: 0.1.0
keywords:
  - WordPress
  - Presslabs
home: https://www.presslabs.org
sources:
  - https://github.com/presslabs/stack
  - https://github.com/presslabs/mysql-operator
maintainers:
  - name: Presslabs
    email: ping@presslabs.com
    url: https://www.presslabs.com
