dependencies:
  - name: mysql-operator
    repository: https://presslabs.github.io/charts/
    version: ~0.2.7
    condition: mysql-operator.enabled

  - name: wordpress-operator
    repository: https://presslabs.github.io/charts/
    version: ~0.3.1
    condition: wordpress-operator.enabled

  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: ~1.6.0
    condition: nginx-ingress.enabled

  - name: cert-manager
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: ~0.6.7
    condition: cert-manager.enabled

  - name: prometheus-operator
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: ~5.7.0
    condition: prometheus-operator.enabled
